### PR TITLE
Model-view pattern drafted, minor fix

### LINKED ISSUE #3: Separate front-end from back-end
Create TaskList and Task classes.
Provide communication between them and UI using the signals/slots mechanism.

### PR DESCRIPTION
**Pull request by topminime**
#3 and #4 to be closed.
note: CModel implements singleton pattern

### CODE REVIEW

**Review by serzap — COMMENTED** [review]
Please don't push this file TodoListApp.pro.user. Git ignore should prevent pushing starting from next commit.

File: CModel.cpp [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+CModel *CModel::theModel = nullptr;
+
+CModel::CModel()
+{
+
+}
+
+CModel *CModel::getInstance()
+{
+    if (!theModel) theModel = new CModel();
```
Comment (serzap) [inline CModel.cpp]: Memory leak. Pls delete allocated memory.

File: CTask.cpp [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+{
+    mStatus = status;
+}
+
+std::string CTask::getDescription() const
+{
+    return mDescription;
+}
+
+void CTask::setDescription(const std::string &description)
```
Comment (serzap) [inline CTask.cpp]: Better use QString

File: CTask.hpp [hunk 3]
```diff
@@ -0,0 +1,25 @@
+#ifndef CTASK_HPP
+#define CTASK_HPP
+
+#include <string>
+
+class CTask
+{
+public:
+    CTask();
+    CTask(std::string description);
```
Comment (serzap) [inline CTask.hpp]: QString

File: CTask.hpp [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+    bool getStatus() const;
+    void setStatus(bool status);
+
+    std::string getDescription() const;
```
Comment (serzap) [inline CTask.hpp]: QString

File: MainWindow.hpp [hunk 5]
```diff
@@ -19,13 +20,15 @@ class MainWindow : public QMainWindow
...
+    void addNewTask(const CTask &task);
     void deleteSelected();
+
 private slots:
     void on_pushButton_NewTask_clicked();
     void on_pushButton_DeleteTask_clicked();
+
 signals:
-    void newTaskButtonClicked();
+    void newTaskButtonClicked(std::string taskName);
```
Comment (serzap) [inline MainWindow.hpp]: const QString&

File: NewTaskWindow.hpp [hunk 6]
```diff
@@ -17,14 +17,14 @@ class NewTaskWindow : public QWidget
     ~NewTaskWindow();
 
 signals:
-    void newTaskCreated(TaskInfo taskInfo);
+    void newTaskCreated(CTask task);
```
Comment (serzap) [inline NewTaskWindow.hpp]: const CTask&

**Review by serzap — COMMENTED** [review]
See comments

File: MainWindow.cpp [hunk 7]
```diff
@@ -17,20 +18,25 @@ void MainWindow::on_pushButton_NewTask_clicked()
...
 }
 
-void MainWindow::updateTaskList(const std::vector<Task> &list)
+void MainWindow::updateTask(const Task& task)
 {
-    mUI->listWidget_Tasks->clear();
-    for (auto task = list.begin(); task != list.end(); task++) {
-        mUI->listWidget_Tasks->addItem(getListItem(*task));
+    QString itemInfo = QString(task.getDescription()+'\t' + task.getDeadline().toString("dd.MM.yyyy hh:mm"));
+    QListWidgetItem* item = new QListWidgetItem(itemInfo);
```
Comment (serzap) [inline MainWindow.cpp]: Memory leak. Implemetation should be changed.
